Add Open Addressing Hash Map
mindxhub/dna-java pull request #12
Opened 2020-06-01 13:16 UTC by RT1918

2020-06-04 08:05 UTC, cuonghq104 approved these changes
Great!!

2020-06-04 08:22 UTC, trungducc commented
@vietduc01100001 Please help to take a look

2020-06-05 06:06 UTC, hellovietduc requested changes
Please create separate PRs for each issue. Don't mix Array or Linked List in Hash Map PR.

Plus, please add test cases and if possible set up GitHub Actions to run it automatically, and everyone can see the result as well.

2020-06-05 06:06 UTC, hellovietduc commented on src/Array.java
> +        arr = new int[0];
Initializing the internal array to be of length 0 is a bad practice. It means for the first 3 items inserted into the array, we have to grow the capacity 3 times! Choose a power of 2 number, 8 or 16 would be a good choice.

2020-06-05 06:06 UTC, hellovietduc commented on src/Array.java
> +        if (index > size - 1) {
What if we pass -1, -2 or -3000 to this function? Would it throw an error? Or should we handle it nicely?

2020-06-05 06:06 UTC, hellovietduc commented on src/Array.java
> +        if (index == size) {
Same as above, you should validate the `index` parameter.

2020-06-05 06:06 UTC, hellovietduc commented on src/Array.java
> +        }
You won't need to handle this edge case if you choose a good default capacity.

2020-06-05 06:06 UTC, hellovietduc commented on src/Array.java
> +            int[] newArr = new int[arr.length * 2];
Avoid hard-coding the grow factor `2` into the function.

2020-06-05 06:06 UTC, hellovietduc commented on src/Array.java
> +        if (index >= size - 1) {
Validate the `index` parameter when it's a negative integer.

2020-06-05 06:06 UTC, vietduc01100001 commented on src/Array.java
> +            int[] newArr = new int[arr.length / 2];
Same as above, avoid hard-coding "magic numbers".

2024-11-18 09:45 UTC, closed without merging